# Generated by Django 3.2.15 on 2022-08-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click On The Link Above Read Post...', max_length=300),
        ),
    ]
